---

is_debug: true
listen:
  type: port
  bind_ip: 0.0.0.0
  port: 10000

storage:
  host: localhost
  port: 5432
  database: cvmaker
  username: papvan
  password: 1234
#  auth_db: admin
#  collection: users
